### ISSUE TITLE
Mileage fields accept non-digits

### ISSUE THREAD

**Issue by monikakrawczak** [CodeForPoznan/pah-fm#114]
On "Add New Route" view fields "Starting Mileage" and "Ending Mileage" accept non-digits (`+`, `-`, `,` and `.`). 
Brower based validation works properly after clicking "Submit" button.

I'm aware that `,` and `.` could be used but `+` and `-` doesn't make sense here.

Tested on Chrome.

**Comment by adamgajzlerowicz** [comment]
https://github.com/CodeForPoznan/pah-fm/pull/163
