### ISSUE TITLE
Behave Tests

### ISSUE THREAD

**Issue by monikakrawczak** [CodeForPoznan/pah-fm#143]
1. Login Testcase
2. Log out Testcase
3. Add New Route Testcase
4. Change Languages (Polish, English, Ukrainian) Testcase

REMEMBER:
- check if input values are validated (letters, special characters, numbers)
- check if pah's logo should change
- check for any error messages
-check if the chosen flag should be highlighted

**Comment by monikakrawczak** [comment]
@yellowee testcase 2 and 4
@monikakrawczak testcase 1 and 3

**Comment by magul** [comment]
@w1stler, @monikakrawczak and @yellowee are working on a list of scenarios to be written in Behave. They would appreciate any input from somebody more experienced here (if You would have time to figure out how business logic looks like here).

**Comment by iansowinski** [comment]
@w1stler @monikakrawczak @yellowee is this issue dead or what?

**Comment by arturtamborski** [comment]
Worked on in https://github.com/CodeForPoznan/pah-fm/pull/358

**Comment by arturtamborski** [comment]
Solved by @kruczyna.
