### ISSUE TITLE
Improvements of logout UX

### ISSUE THREAD

**Issue by iansowinski** [CodeForPoznan/pah-fm#145]
App should prevent user from accidentialy logging out and asure users that operation was succesful.

**AC**:
* Create a confirmation pop-up - if users clicks log-out button, they should confirm that they are sure thay want to do it.
* Create "thank you" and confirmation screen or message after logging out for users to be sure that operation was succesful.
* Users should not have option to log out when they are offline - **TBD**

**Comment by adamgajzlerowicz** [comment]
@monikakrawczak 
To be confirmed with the customer

**Comment by monikakrawczak** [comment]
Split for 3 tasks.
