### ISSUE TITLE
Improvement of form new route UX

### ISSUE THREAD

**Issue by iansowinski** [CodeForPoznan/pah-fm#146]
Adding new route is probably most engaging and time-consuming part of our app. I propose here some imprvements we can take to make this expierience better:

* Choose a car
  * If there will be a lot of cars to choose from, there should be some options to filter the list.
  * If it's common for single driver to ride usually the same car, maybe it's good option to have it preselected by default for the second time they use it.
* Passangers
  * Typling to the box should filter selector - now it doesn't provide any value.
* Description
  * Should be textarea
* Start and End location
  * Should propose locations entered before
* Miscellaneous
  * Succes and error message - after submiting form user should see feedback that route was (or was not) added to routes and somehow synced, or not.

**Comment by adamgajzlerowicz** [comment]
@OlaPAH @monikakrawczak 
Here are some ideas for ux improvement. Can we confirm if they are required, and if so, break them to smaller tasks and add to sprint?

Thanks

**Comment by iansowinski** [comment]
to be refined
