### ISSUE TITLE
Drives: create form

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/pah-fm#15]
Fields:
 * description
 * start_mileage
 * end_mileage
 * distance (auto-generated based on mileage)
 * car (dropdown)
 * passengers (multi select, maybe: https://vue-multiselect.js.org/)
 * project (dropdown)
 * from
 * to

Order them as you see fit.
Must be responsive and reasonably good-looking.
All fields are required.

Edited by @jacol12345

**Comment by weronikafelczak** [comment]
Fields:
 * description - DONE
 * start_mileage - DONE
 * end_mileage - DONE
 * distance (auto-generated based on mileage) - TO DO
 * car (dropdown) - DONE
 * passengers (multi select, maybe: https://vue-multiselect.js.org/) - TO DO
 * project (dropdown) - TO DO
 * from - DONE
 * to - DONE

**Comment by weronikafelczak** [comment]
Closed. Remaining tasks will be done with issue #106.
