### ISSUE TITLE
Passenger language

### ISSUE THREAD

**Issue by adamgajzlerowicz** [CodeForPoznan/pah-fm#156]
Passenger should be have language assigned to them.

This should be used in:

- email
- confirmation page
- interface language

**Comment by werginia** [comment]
@werginia

**Comment by jacol12345** [comment]
This ticket will be done in two parts.

Backend:
@werginia will build the backend part up to a point where API sends "country" field with response to /api/users/me request.

Frontent:
Frontend will set the language to user's language.
It will also store the language in local storage to set the language correctly when working offline.

**Comment by magul** [comment]
That shold not be `country` field, rather `language` one (ideally using `ISO 639-2`)

**Comment by lukaszmaterla** [comment]
Duplicated with Add a "locale" field to passenger to and when sending email send appropriate email content #107

**Comment by magul** [comment]
Closing as at least for now we're not going to send emails and passenger will not have access to the app directly.
