### ISSUE TITLE
[MVP] Complete the translation into Ukrainian

### ISSUE THREAD

**Issue by monikakrawczak** [CodeForPoznan/pah-fm#170]

**Comment by monikakrawczak** [comment]
@juliaanholcer

**Comment by monikakrawczak** [comment]
The information about entering the required data is still mix polish and english.
![ukr.png](https://images.zenhubusercontent.com/5c4dca57fa72607b5c6230d4/1d5ac30e-ae00-45d3-a699-5f92e36ac36d)

**Comment by adamgajzlerowicz** [comment]
How about we remove the error messages altogether? It will be a hustle to translate the errors (messages are auto generated based on the field name) and they are waaaay at the top of the screen, so user is likely not to see them anyway. 

If there are errors, thee user will see the red border to let them know something is wrong.

**Comment by monikakrawczak** [comment]
Yes! I think it's good idea :)

**Comment by monikakrawczak** [comment]
Ok, so are we going to leave it as it is now? Or you want to change it as you said before, @adamgajzlerowicz?
Because if you prefer to leave it as it is now, we can move this issue to ,,Done"

**Comment by adamgajzlerowicz** [comment]
I am closing this for now. We are aware of this issue. Lets do some inital testing with users and findout if they do find erors helpfull. If they do - we will make a task to translate. If will say "what error messages?" then we can just remove them
