### ISSUE TITLE
[MVP] Downloading reports

### ISSUE THREAD

**Issue by monikakrawczak** [CodeForPoznan/pah-fm#174]
Add the ability to download reports from Django Admin.

**Comment by adamgajzlerowicz** [comment]
@konrad

**Comment by konrad** [comment]
@adamgajzlerowicz - I assume you pinged the wrong username here.

**Comment by adamgajzlerowicz** [comment]
Yeah dude - sorry :)

**Comment by adamgajzlerowicz** [comment]
Ola confirmed - mvp version is looking good so we are going to release it.
