### ISSUE TITLE
Log Sheet examples

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/pah-fm#18]
To figure out business context:
[Annex_17.xlsx](https://github.com/CodeForPoznan/pah-fm/files/2511562/Annex_17.xlsx)
[PAH.LogSheet.xlsx](https://github.com/CodeForPoznan/pah-fm/files/2511564/PAH.LogSheet.xlsx)

**Comment by danutaj23** [comment]
Cyrillic! :open_mouth:

**Comment by danutaj23** [comment]
@OlaPAH, przez kogo jest definiowana wartość `Consumption 10l per 100 km`, którą mamy w pliku PAH.LogSheet.xlsx? Czy ta wartość jest stała dla konkretnego samochodu?

**Comment by danutaj23** [comment]
@OlaPAH, w pliku Annex_17.xlsx nie każda wartość `End KM` jest równa `Start KM` z kolejnego wiersza. Co się dzieje z samochodem w międzyczasie? Czy jest wykorzystywany przez innego kierowcę i trasa jest rozliczana na innej karcie? Czy jednak takie sytuacje nie powinny mieć miejsca?

**Comment by OlaPAH** [comment]
Hej, niestety nie bede w stanie odpowiedziec do  wtorku bo jestem w Izraelu i nie mam kompa. Ale przesle te pytania do ludzi w biurze, moze odpowiedza szybciej.

**Comment by OlaPAH** [comment]
Hej! Mam odpowiedź, trochę późno, ale jednak. 
1. Consumption - założymy stałą dla każdego samochodu i będziemy się jej trzymać, bo nie będzie komu tego sprawdzać na bieżąco.
2. End KM nie może się zawsze równać Start KM, bo samochody są wypożyczane z kierowcą, który może w międzyczasie jeździć gdzie indziej.

**Comment by magul** [comment]
Closing as we have a simple reporting solution in place. Will refine later.
