### ISSUE TITLE
Remove possibility to choose a car from list.

### ISSUE THREAD

**Issue by monikakrawczak** [CodeForPoznan/pah-fm#202]
There's a relation of one-to-one between car and a driver.

We should attach that relation in Django Admin and remove option to choose a car on Drive form.

**Comment by m-recz** [comment]
@m-recz

**Comment by iansowinski** [comment]
To refine 15.01.2019

**Comment by monikakrawczak** [comment]
AC:
- put the country to user model
- put the country to car model

**Comment by monikakrawczak** [comment]
This issue is closed in favor of #253 and #254
