### ISSUE TITLE
Feedback about the driver

### ISSUE THREAD

**Issue by monikakrawczak** [CodeForPoznan/pah-fm#204]
Add an option for passengers to share feedback about the driver. 
Feedback should be related with Django Admin and visible just only to Admin in a report.

**Comment by adamgajzlerowicz** [comment]
Will be worked on after first iteration of reports is finished

**Comment by jacol12345** [comment]
Can we add it now and show it in Django admin in next step?

**Comment by OlaPAH** [comment]
To be discussed later - not necessary at this stage.
