### ISSUE TITLE
check application offline working

### ISSUE THREAD

**Issue by adamgajzlerowicz** [CodeForPoznan/pah-fm#223]
Service worker is not installing correctly on production build. Investigation around it is required as when offline application won't open

**Comment by jacol12345** [comment]
Checklist:

- `index.html` is not cached
- `service-worker.js` is not cached
- `service-worker.js` is constructed manually and tracked by VCS to make managing it more explicit
- JS and CSS assets are cached infinitely on prod (they contain hash so it's ok)
- JS and CSS assets are not cached locally (hot reloading)
- Service Worker cache is cleared when user logs out
- list of drives is cached
- driver details are cached
- driver can add a drive even if offline
- drive is notified if drive is added offline
- drive added offline is shown on list of drives as "pending"
- when app is offline, Service Worker loads last `index.html` and assets cached by browser, resulting in page fully loaded
- login page indicates that driver is offline

**Comment by monikakrawczak** [comment]
done in #288
