### ISSUE TITLE
Total mileage in current month

### ISSUE THREAD

**Issue by OlaPAH** [CodeForPoznan/pah-fm#239]
Hej, Valik napisał, że kierowcy bardzo się cieszą, że dodaliśmy pole "total mileage", ale lepiej sprawdzałaby się ilość kilometrów przejechanych w danym miesiącu. Jest szansa na zmianę?

**Comment by juliaanholcer** [comment]
Change total mileage function to filter only drives from the current month.

**Comment by Loczi94** [comment]
@Loczi94

**Comment by monikakrawczak** [comment]
merged
