### ISSUE TITLE
Update Car model

### ISSUE THREAD

**Issue by danutaj23** [CodeForPoznan/pah-fm#24]
We need Car to have the following fields:
* plates
* description (optional)
* mileage_unit (km/mi)
* fuel_consumption (litres/km)

All fields are accessible from Django Admin.

**Comment by JohnCleese** [comment]
Maybe we should include the units for distance and fuel volume?

**Comment by jacol12345** [comment]
We need the car to have the following fields:
* plates
* description (optional)
* mileage_unit (km/mi)
* fuel_consumption

Also please make sure that all these fields are accessible from Django Admin.
