### ISSUE TITLE
App freezing

### ISSUE THREAD

**Issue by OlaPAH** [CodeForPoznan/pah-fm#241]
The driver, (login: aleksei311086@ukr.net) can't do anything when entering the "add ride" table - first of all, he's only able to see one car number, and it's not Ukrainian (probably, from South Sudan or Somalia), and all the lines to fill in aren't active, he can't even change the date or do anything. At the same time, he has no problems logging in, unlike some other drivers I was describing earlier.

**Comment by adamgajzlerowicz** [comment]
I requested today details to sign in as this user. 
Other thing to try is to clear site data in the browser and start fresh

**Comment by adamgajzlerowicz** [comment]
@OlaPAH confirmed that the problem resolved it's self. 
![image](https://user-images.githubusercontent.com/675615/64067925-40d97380-cc30-11e9-8205-24fa89afb6a0.png)
I am closing the ticket for now - if there are any other issues we will create another ticket
