### ISSUE TITLE
Missing package after deployment

### ISSUE THREAD

**Issue by Maciek246** [CodeForPoznan/pah-fm#242]
During last deployment application by Ansible package `django-import-export` was not installed.
We have to investigate and fix that issue.

AC:
- Every deployment install properly all required packages
- Application doesn't throw HTTP 500 error

**Comment by arturtamborski** [comment]
The current way of managing production with ansible playbooks is rather fragile, unfortunately.

I've set up a live-like instance of pah-fm on one of my servers and have not encountered this problem, though it would be probably much better to just abandon the playbooks and just use docker & docker-compose as we do for the development stack, as it's way more reliable.

Sadly, I'll have to mark that as closed and wont-fix as we don't have enough time to spend on investigating that problem. Hope we'll migrate to lambda soon enough to not care about that any more.
