### ISSUE TITLE
Django Admin - exports

### ISSUE THREAD

**Issue by monikakrawczak** [CodeForPoznan/pah-fm#250]
In Django Admin **export,** add driver's name and surname instead of email

**Comment by arturtamborski** [comment]
@arturtamborski

**Comment by magul** [comment]
@monikakrawczak @OlaPAH right now we're exporting drivers first name and last name but they are stored in separate columns (see screenshot). Wouldn't it be more beneficial to have the first name and last name in the same column (as that's what unambiguously define driver)? (@arturtamborski we have a function `dehydrate_passengers` which create sophisticated value from two columns in passengers table).

**Comment by monikakrawczak** [comment]
After consultation with Ola, the name and surname should be in one column
