### ISSUE TITLE
Passenger - country

### ISSUE THREAD

**Issue by monikakrawczak** [CodeForPoznan/pah-fm#256]
Passengers may be assigned to one country.
If the passenger is not assigned to the country, the passenger should be visible in every country.

**Comment by monikakrawczak** [comment]
Passenger list for driver only in the same country (or not set)

**Comment by Ctilhs** [comment]
@Ctilhs

**Comment by Ctilhs** [comment]
https://github.com/CodeForPoznan/pah-fm/pull/326
