### ISSUE TITLE
Drive list - filter by country

### ISSUE THREAD

**Issue by monikakrawczak** [CodeForPoznan/pah-fm#257]
In Django Admin, in drives list, add the possibility of filtering by country.

**Comment by monikakrawczak** [comment]
@KarolJagodzinski

**Comment by pniedzwiedzinski** [comment]
I would like to do this

**Comment by arturtamborski** [comment]
Sure, go ahead :)

**Comment by pniedzwiedzinski** [comment]
Drive model has no country property. By what should I filter it?

**Comment by arturtamborski** [comment]
Every `drive` is created and updated by `Drive.driver` which is a relation to `User` model, so you should filter it by `Drive.driver.country` property.

**Comment by pniedzwiedzinski** [comment]
I made a simple filter, but it lists all countries:
![image](https://user-images.githubusercontent.com/19212948/64082418-f844b780-cd0e-11e9-9796-a730dc5a0bc5.png)

Is it okay or should it show only countries from existing drives?

**Comment by arturtamborski** [comment]
It's okay as we intend to significantly limit the amount of countries anyway (maybe as another table?).
Anyway, looks great! I'll test it on my side and see if there's nothing more to do with this.
Thanks!
