### ISSUE TITLE
Make close sidebar menu button bigger

### ISSUE THREAD

**Issue by iansowinski** [CodeForPoznan/pah-fm#264]
When we open sidebar menu with the "hamburger" button, "X" button which replaces it is much smaller and moved to the top left. This is anti-antippatern because it should be possible to just click in the same place for the second time to close the menu. We should move the "X" button to the same place where the "hamburger" button is before opening menu.

**Comment by arturtamborski** [comment]
Thanks for this fix Julia! :)
