### ISSUE TITLE
HTTP 500 when entering `/admin`

### ISSUE THREAD

**Issue by arturtamborski** [CodeForPoznan/pah-fm#273]
Server returns HTTP 500 when entering `/admin` URL, but works fine for `/admin/` (notice the last forward slash).

**Comment by adamgajzlerowicz** [comment]
I am not getting 500, but there is this annoyance where you need to provide slash at the end to get to admin. Lets remove that

can it be as simple as 
https://github.com/CodeForPoznan/pah-fm/pull/299
?

**Comment by adamgajzlerowicz** [comment]
The above is merged. If you are still having issues please re-open the ticket
