### ISSUE TITLE
Replace PDB with IPDB for interactive sessions with debug-backend

### ISSUE THREAD

**Issue by arturtamborski** [CodeForPoznan/pah-fm#283]
There's really no point in using PDB in favor of IPDB in my opinion.
One of the biggest advantages is the code-completion mechanism, but it also supports syntax coloring and much more.

The issue itself should be easy to implement, it probably will require replacing pdb with ipdb in requirements.txt but I might be slightly wrong on this.

**Comment by magul** [comment]
I'm fine with adding `ipdb` and `pdbpp` into `requirements-dev.txt`. Also was thinking about going into `Pipfile` and `pipenv`.

**Comment by Ctilhs** [comment]
@Ctilhs I will add it.

**Comment by arturtamborski** [comment]
We've not settled up with a decision for package manager so we're staying with pip for now.
