### ISSUE TITLE
Update fields of Route model

### ISSUE THREAD

**Issue by jacol12345** [CodeForPoznan/pah-fm#29]
Route fields:

- driver
- car
- passengers
- date
- start_mileage
- end_mileage
- project
- description
- from
- to

Mileage - just make it a DOUBLE. We don't care about units as unit will be extracted from the car.

All fields are accessible from Django admin interface.

**Comment by danutaj23** [comment]
@OlaPAH, is mileage always in kilometers?

**Comment by jacol12345** [comment]
We can later on define km/miles in car. User will just enter what they see on the car display.
