### ISSUE TITLE
Initial Admin users - add any country value.

### ISSUE THREAD

**Issue by Ctilhs** [CodeForPoznan/pah-fm#294]
In last update field country was added to User model.
Value in field country for initial admin users:
- hello@codeforpoznan.pl
- ola@pah.org.pl
Defaultly don't have any country set for it.

So we don't get any cars in response.
https://i.imgur.com/eXM8e4f.png

After updating field country for any of this users with proper Country value, things getting back to normal.
https://i.imgur.com/ZQVXGmr.png

Will it work if we modify create_admin.py to accept one more argument specifying country. And update docker-entrypoint.sh to set any country for this users? Is there better solution?

**Comment by adamgajzlerowicz** [comment]
How about we remove this command entirely and use "populate database" instead.
I don't think we need two seeding mechanisms.

**Comment by arturtamborski** [comment]
I'm all in for Adam's change, though I'd also want to distinguish the default users somehow because these accounts shouldn't appear in exports.

Maybe we could use separate group? We could also use already existing fields in `User` model for hiding them - for example `is_staff` or some custom one.

**Comment by adamgajzlerowicz** [comment]
How about this?

https://github.com/CodeForPoznan/pah-fm/pull/298

**Comment by magul** [comment]
Ok, just found that one (after doing a review in #298).

> I don't think we need two seeding mechanisms.
`make populate_database` is for the generation of factories and `python manage.py create_admin` is right now used only in `docker-entrypoint.sh` to create to the initial superusers. From my perspective, these serve two separate purposes.

> these accounts shouldn't appear in exports.
Unless they create drive, they should not be visible in an export. And would be strange, if we would exclude them even if they added some drives.

We had yesterday refinement regarding passenger's signing drives (still waiting for @monikakrawczak to transfer them to GitHub) and we agreed then to migrate `Passenger` model to `User`. We also agreed (way before yesterday) that passenger may belong to one country, but don't need to. Users (passengers) without country set should be listed for every driver list.

I would assume, that superusers should be treated as a passenger (not a driver) so `Add new drive` form is not intended for them.

@Ctilhs protip: you can paste graphics files directly into GitHub comments/description.

**Comment by adamgajzlerowicz** [comment]
I agree - lets keep it as simple as we can. If user has a drive, it will show in report. No matter who the user is.
In regards to model migration - I believe that will left to be done as a last step. We prepare certificates, frontend, etc first.

I am continuing discussion about migration scripts here
https://github.com/CodeForPoznan/pah-fm/pull/298/files/fd6c69cacb6af00c27224ef804fd3130c90560fa#diff-096359d9dbf21d9492d718f9363ea5e5

**Comment by magul** [comment]
AFAIR on refinement, we figure it out that migration of `Passenger` model into `User`s will be one of the first steps that will proceed. We just need to ensure, that:
 * we use different serializer for passengers list and for the current user
 * we ensure a smooth transition for in serializer and endpoint.

After that, we have migration on `User` mode to add fields for cryptographic keys. I believe we need to wait for @monikakrawczak to prepare that backlog.

**Comment by adamgajzlerowicz** [comment]
That sounds good!
Before we change passengers into users, we need ability to separate them into groups
https://github.com/CodeForPoznan/pah-fm/pull/293 ;)

**Comment by magul** [comment]
#293 is next on my list to review. :)

**Comment by arturtamborski** [comment]
Related issue: #352 
Related PR: #353 
Closing.
