### ISSUE TITLE
Don't use `random.radint` in `Factory` definition

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/pah-fm#296]
Use `fuzzy.FuzzyInteger` instead.

Issue introduced here: https://github.com/CodeForPoznan/pah-fm/blob/6083c926262ce868b964a117b8129eebd43f31af/backend/fleet_management/factories.py#L153

There's also `import random` twice.

**Comment by adamgajzlerowicz** [comment]
Here you go ;)
https://github.com/CodeForPoznan/pah-fm/pull/297
