### ISSUE TITLE
Roles (groups) to distinguish drivers and passengers

### ISSUE THREAD

**Issue by monikakrawczak** [CodeForPoznan/pah-fm#309]
Add `User` role (or use group from `django.contrib.auth`) to distinguish drivers and passengers (expose role/group in serializer).

**Comment by magul** [comment]
@adamgajzlerowicz didn't you do that in #293 and #307?

**Comment by arturtamborski** [comment]
Yup, looks like he did. Closing for now, seems to be resolved.
