### ISSUE TITLE
New app version

### ISSUE THREAD

**Issue by jacol12345** [CodeForPoznan/pah-fm#31]
0) App is served from cache.
1) When new app is available, there is an alert displayed to the user "New version available. Refresh the page to load new version."
2) When user closes the app and opens it again OR reloads the page, new app version is used.
3) Documentation regarding testing this feature is available (on Chrome with mobile view + locally with phone connected over USB in debug mode Chrome).

NICE-TO-HAVE
styled popup instead of alert

**Comment by magul** [comment]
Do we need to have backend here, or will PWA know based on ETag or some hash in asset name?

**Comment by jacol12345** [comment]
It will be based on asset name. If available, the last version will be loaded from cache. New version is then fetched and SW knows, that it can update.
When developing this task we need to also figure out how to handle breaking changes in backend and users with old version of app.

**Comment by adamgajzlerowicz** [comment]
I can't assign myself of change labels :(

Made a pr though

**Comment by adamgajzlerowicz** [comment]
Why is this reopened?

**Comment by jacol12345** [comment]
Misclick in Zenhub (issue tracker). Sorry!
