### ISSUE TITLE
Add private/public RSA key to User model

### ISSUE THREAD

**Issue by monikakrawczak** [CodeForPoznan/pah-fm#311]
Extend User model with fields for: `rsa_modulus_n`, `rsa_pub_e`, `rsa_priv_d`.
All of them should be strings, length 6 characters.

**Comment by adamgajzlerowicz** [comment]
Are there any specific guidelines to follow? Like standard specification? Or is up to the person that implements the feature?

Thanks!

**Comment by monikakrawczak** [comment]
@magul could you please put a comment?

**Comment by magul** [comment]
@adamgajzlerowicz more details will be in a separate ticket (to implement key generation algorithm). This one is limited only for database model migration. Will update description here to list all fields requirements.

**Comment by Ctilhs** [comment]
@Ctilhs

**Comment by magul** [comment]
Done in #360
