### ISSUE TITLE
Current user serializer

### ISSUE THREAD

**Issue by monikakrawczak** [CodeForPoznan/pah-fm#316]
Update current user serializer to include user roles (groups), `rsa_modulus_n`, `rsa_pub_e` and `rsa_priv_d` (be careful to not leak `rsa_priv_d` to any other serializer).

**Comment by Gerthol** [comment]
@Gerthol take this task

**Comment by arturtamborski** [comment]
Any progress on that, @Gerthol ? It's blocking the #319
