### ISSUE TITLE
Dane początkowe się nie zapisują

### ISSUE THREAD

**Issue by OlaPAH** [CodeForPoznan/pah-fm#329]
Sergiej przekazał mi następujący problem: kierowcy nie korzystają z aplikacji w sposób w jaki powinni z prostego względu - gdy mają stały zasięg i dostęp do netu zdarza im się korzystać z internetu pomiędzy wpisaniem danych początkowych i danych dotyczących zakończenia przejazdu. I dane początkowe się nie zapisują. Czyli: wprowadzają starting point i mileage. Potem jadą w trasę. Grzebią w internecie. Potem dojeżdżają do celu, chcą wpisać dane końcowe, ale to co wprowadzili się nie zapisuje, więc musza to robić od początku. Z tego względu wolą spisywać dane na papierze i wieczorem w domu przepisują dane z papieru do aplikacji. Czy możemy temu jakoś zaradzić?

**Comment by monikakrawczak** [comment]
Closed by #330
