### ISSUE TITLE
Menu button

### ISSUE THREAD

**Issue by pniedzwiedzinski** [CodeForPoznan/pah-fm#345]
Shouldn't hamburger icon and close icon be in the same place?
![image](https://user-images.githubusercontent.com/19212948/64732848-dc49ce80-d4e3-11e9-8afa-55d1be716537.png)
![image](https://user-images.githubusercontent.com/19212948/64732865-e53aa000-d4e3-11e9-9d09-795ff4d7bbcf.png)

**Comment by arturtamborski** [comment]
I believe that's already fixed here https://github.com/CodeForPoznan/pah-fm/pull/344
Have you tested that on a fresh pull from `upstream/develop`?

**Comment by pniedzwiedzinski** [comment]
No, sorry, my fault
