### ISSUE TITLE
Problems with adding passenger

### ISSUE THREAD

**Issue by OlaPAH** [CodeForPoznan/pah-fm#351]
Reporting another issue with the tool: 
I am adding new passengers through the admin page, but the driver doesn’t see the added passengers for some reasons. Refreshment o the page doesn’t help, internet is fine. 
And I see them new passengers on my page in the tool.
We were standing next to each other and were directly witnessing this glitch

**Comment by magul** [comment]
@OlaPAH I've just tried to recreate the issue on my local environment (using exactly the same version as is on production) and was not able to do so.

Can somebody confirm, that:
 * it's still an issue
 * it happened even when reload is triggered (that's usually dragging webpage content to down of the screen
 * it happened also when the user logs in using a desktop browser

If so, please provide (on Slack) login and password of a driver that has such an issue.

Thanks in advance!

**Comment by magul** [comment]
As we decided on a call with @OlaPAH due to inactivity we're closing that one. If that problem still occurs please create a new ticket.
