### ISSUE TITLE
Containers are running with root privileges on local development environments

### ISSUE THREAD

**Issue by arturtamborski** [CodeForPoznan/pah-fm#356]
Django's `makemigrations` will create new file in `pah-fm/fleet_management/migrations` which will end up owned by user `root` (at least on linux platform).
That's because we build and run our containers as root (again, on linux), and we have to fix that.

One way of doing it is to pass around `$UID` to Dockerfile during build via docker-compose and Makefile and then export that info every time docker container is touched.

**Comment by magul** [comment]
`id -u` to determine user id  in shell-agnostic way.

**Comment by arturtamborski** [comment]
> So you want to have application run with your UID from host?
Yes, I believe on local development environment it's much more sensible to do.

Production environment looks quite different currently and will change even more soon (TM) so this problem does not affect it in any way.

**Comment by arturtamborski** [comment]
i think this is no longer an issue? I can't reproduce it.
