### ISSUE TITLE
Podział na kraje

### ISSUE THREAD

**Issue by OlaPAH** [CodeForPoznan/pah-fm#374]
Hej,
Co do podziału na kraje - jasne, zaczynamy od Ukrainy i to jak najszybciej, żeby to jeszcze przetestować. Natomiast kolejne do włączenia będą:
Irak - jeśli zdążymy to od początku stycznia
Sudan Południowy/Somalia - od początku lutego
Jemen - od początku marca albo od początku kwietnia

**Comment by arturtamborski** [comment]
Hej, kraje wymienione przez Ciebie są już w aplikacji (zapisane są po angielsku), natomiast samo filtrowanie po kraju mogłoby być pewnie wygodniejsze, więc założyliśmy nowy Issue #376.
Feature który tam opisaliśmy to dodanie kolumny z krajem dla danego przejazdu w panelu admina.

**Comment by arturtamborski** [comment]
Dodaliśmy wspomnianą kolumnę, wygląda to teraz mniej więcej tak:
![image](https://user-images.githubusercontent.com/8676740/72209807-f35cf500-34b2-11ea-9c19-318a3835f7d7.png)
wartość w `Country` to kraj kierowcy z danego przejazdu.

**Comment by arturtamborski** [comment]
Dodaliśmy kolejną kolumnę, tym razem z informacją o tym czy przejazd został poprawnie zweryfikowany podpisem cyfrowym pasażera:
![image](https://user-images.githubusercontent.com/8676740/72668414-cc5c7100-3a26-11ea-9e9f-1300f611ff2f.png)

Powinno się sprawdzić :dancer: 

Pozwolę sobie zamknąć ten ticket - stwórz proszę nowy jeśli będziesz miała więcej pomysłów na usprawnienie Waszej pracy :)
