### ISSUE TITLE
Licencja

### ISSUE THREAD

**Issue by Piegusek07** [CodeForPoznan/pah-fm#375]
@magul jaką obecnie macie licencje w kodzie apki dla PAH'u?

Chciałabym się upewnić, że skoro ma to być aplikacja, z której teoretycznie każdy może skorzystać to nikt np. nie sprzeda jej nigdy sobie jako swój produkt/nie wykorzysta kodu. Zależy jakie mamy oczekiwania od licencji i jak chcemy by aplikacja/kod była chroniona/czy w ogóle chcemy ją chronić jako właśność CfP?

- Licencja GNU lub CPL

**Comment by magul** [comment]
@Piegusek07 

Nie to że zaskoczyło mnie pytanie, ale zaskoczyło mnie to, że w kodzie nigdzie nie mamy podanej licencji. Skończy się na tym, że będziemy musieli wszystkich kontrybutorów spytać, czy zgadzają się na daną licencję, a jeżeli nie, to nie do końca wiem jak się zachować.

W każdym razie ja planowałem żeby to było MIT LIcense (https://opensource.org/licenses/MIT). Ona jest dosyć liberalna, więc AFAIK każdy może używać i odsprzedawać tę aplikację według własnego uznania. My z założenia mieliśmy zawsze robić open source, więc nas to w ogóle nie boli. Nie sądzę też by ta aplikacja miała duży potencjał komercyjny.

**Comment by magul** [comment]
Otwieram, bo trzeba tę licencję dodać do repozytorium i ustalić z wszystkimi kontrybutorami, że oni są tutaj na okejce.
