### ISSUE TITLE
Drive form errors are not translated after switching language

### ISSUE THREAD

**Issue by arturtamborski** [CodeForPoznan/pah-fm#380]
![image](https://user-images.githubusercontent.com/8676740/70550458-11fb6380-1b76-11ea-94d2-a4bb3ec83fd2.png)

**Comment by pniedzwiedzinski** [comment]
On which branch have you encountered it?

**Comment by arturtamborski** [comment]
on `develop`. Just tested with the latest one (Latest commit `baa2ee7`).

**Comment by pniedzwiedzinski** [comment]
Ok, I reproduced it. That's because errors are stored as strings. I don't think it's necessary for the next release since there would be a lot of changes to be made.

**Comment by pniedzwiedzinski** [comment]
I have an idea of how to do it easily! Instead of storing errors as "translated" string, we could pass the translation identifier:

`this.$t('drive_form.end_mileage_error')` => `'drive_form.end_mileage_error'`

and then in `ErrorList` component use `$t`

Now it sounds so easy 😛

**Comment by bckamil** [comment]
@bckamil

**Comment by arturtamborski** [comment]
@bckamil any progress on that?
