### ISSUE TITLE
Value written in start mileage / end mileage are not removable

### ISSUE THREAD

**Issue by arturtamborski** [CodeForPoznan/pah-fm#381]
![image](https://user-images.githubusercontent.com/8676740/70550631-52f37800-1b76-11ea-80e9-59b20e2fb5c4.png)
There's something wrong with these two number fields - I can't remove value from them with delete or backspace. I can't remove digits, I can only add new ones. The only way of decreasing the value is to use the "arrow down" button, on the right side of the input box.

**Comment by pniedzwiedzinski** [comment]
That seems strange and I couldn't reproduce it. What browser is it?

**Comment by arturtamborski** [comment]
Firefox v60 (quantum)

**Comment by pniedzwiedzinski** [comment]
https://stackoverflow.com/questions/49263039/backspace-not-working-in-firefox-in-input-field
That's funny.
It looks like firefox can't do this

**Comment by pniedzwiedzinski** [comment]
Ok, this example works just fine. Since it's a quick fix I will do this in #361.
