### ISSUE TITLE
Can submit a form with empty values after sending the filled up one

### ISSUE THREAD

**Issue by arturtamborski** [CodeForPoznan/pah-fm#382]
![image](https://user-images.githubusercontent.com/8676740/70551666-3d7f4d80-1b78-11ea-9537-7e385f8c1167.png)
Steps to reproduce:
1. Fill up form
2. Submit
3. Click submit again
Notice that after step 2. form was cleared but you still could send the form (see network logs for details). Request fails with 400, but the form is sent after _incorrect_ validation.

**Comment by pniedzwiedzinski** [comment]
Probably #361 will fix this

**Comment by pniedzwiedzinski** [comment]
Couldn't reproduce after the #361 was merged.

**Comment by arturtamborski** [comment]
Yup, it's solved now.
