### ISSUE TITLE
Allow filtering of Project and Car select boxes in New Drive form

### ISSUE THREAD

**Issue by arturtamborski** [CodeForPoznan/pah-fm#383]
![image](https://user-images.githubusercontent.com/8676740/70553773-0e6adb00-1b7c-11ea-9ebc-1076908fe451.png)

It would be cool to filter it while typing and also save last selected option in local storage, similarly to passengers' input field.

**Comment by arturtamborski** [comment]
@kruczyna take a look at this one :)

**Comment by natalix** [comment]
@natalix
