### ISSUE TITLE
Behave automation - scenarios

### ISSUE THREAD

**Issue by kruczyna** [CodeForPoznan/pah-fm#385]
**Login page**:
- User opens pah-fm login view - **covered**
- User successfully logs in to pah-fm system with valid credentials - **covered**
- User can't login with invalid credentials - **covered**
- User can't click login button when he didn't input email - **covered**
- User can't click login button when he didn't input password - **covered**
- User sees proper translations after language switch -  **covered**
- User doesn't loose inputted data when language is switched - **covered**

**Logout page**:
- User is able to logout via main menu logout button - **covered**
- User is able to logout via link - **covered**
- User is able to navigate to login page via login again button - **covered**

**Add new drive page**:
- User is able to add a new drive - **covered**
- User sees proper error message when one of required fields is missing - **covered**
- User sees proper translations after language switch  
- User doesn't loose inputted data when the tab was closed and reopened 

**Confirm drive page**
- User is able to confirm a drive with correct input - **covered**
- User is not able to confirm a drive with incorrect input - **covered**
- User doesn't see driver code when navigating back from confirmation code page  - **covered**
- User is able to confirm a drive after input correction  - **covered**
- User sees proper translations after language switch  

**Drives page**:
- User is able to see a newly added drive - in progress
- User is able to navigate to add new drive page via main pah logo - in progress
- User sees proper translations after language switch

**Comment by arturtamborski** [comment]
I'd add few more:

**Add new drive page**:
- User doesn't loose inputted data when the tab was closed and reopened

**Passenger page**:
- User is able to input the drive checksum
- User is able to generate the code for driver

Also, the `User sees proper translations after language switch` doesn't need to be repeated in each page, we probably just need to check that one time (let's say during logging in).

**Comment by kruczyna** [comment]
Added missing scenarios and deleted the `translations` scenario from **Add new drive page**.

**Comment by arturtamborski** [comment]
This ticket is no longer pursued, closing.
