### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by jacol12345** [CodeForPoznan/pah-fm#39]
Yes, we need translations!

Investigate how to do translation best (the simpler the better) and whether we need to touch backend part at all.
There won't be much text in the frontend so we don't need specialised tools.

Create tickets for internationalising app:
* button to switch language
* docs on how to translate new messages

Fallback language: English?

**Comment by magul** [comment]
@OlaPAH Can You determine, which languages we need to support? We will provide a list of sentences to be translated and would love to get translated list in return.

**Comment by OlaPAH** [comment]
Hi,
We definitely need English, then Russian and Polish for now.
I will ask logisticians on missions about other language versions.

**Comment by jacol12345** [comment]
Closed by https://github.com/CodeForPoznan/pah-fm/pull/58.
