### ISSUE TITLE
Display country field in Django Admin as an additional column in Project's list

### ISSUE THREAD

**Issue by arturtamborski** [CodeForPoznan/pah-fm#391]
![image](https://user-images.githubusercontent.com/8676740/71130347-e9b4da00-21f1-11ea-8e13-0cd547a07bf9.png)
Every project has a country related to it, so it would be cool to see it right away in the list view, as an additional column. It should be also filterable.

**Comment by hkaczmarek90** [comment]
It's similar to my last commit - I can do that also.

**Comment by arturtamborski** [comment]
Done - this column now displays project (which underneath is a driver's country).
Thanks for your work.
