### ISSUE TITLE
Replace 'passengers' POST param with 'passenger'

### ISSUE THREAD

**Issue by arturtamborski** [CodeForPoznan/pah-fm#395]
For historical reasons, POST request to `/api/drives` is accepting a `passengers` list containing map with their `id`s. This is no longer valid according to current project requirements - we can safely limit the endpoint so that it accepts single passenger, just like we accept single car or project.

To solve this one would have to take a look into `DriveSerializer` and rewrite `passengers` form field  to `PassengerSerializer` instance with appropriate constraints. More so, it would be nice to also remove the unnecessary mapping in `handleSubmit()` on frontend site.

That's also a good opportunity to write more tests, of course :) Some ideas include checking if request fails with `HTTP_40*` when some fields are not provided, or when some of them have incorrect data and/or type.

**Comment by arturtamborski** [comment]
Also, it would be cool to actually show the Passenger that was assigned to given drive in /drives/ view.

**Comment by OtisRed** [comment]
Might be not relevant but it'll come back if it actually makes troubles
