### ISSUE TITLE
Drives: sync once network is available

### ISSUE THREAD

**Issue by jacol12345** [CodeForPoznan/pah-fm#40]
Once the user is logged and on-line the routes they created while offline are synced with the backend.

**Comment by adamgajzlerowicz** [comment]
Blocked by https://github.com/CodeForPoznan/pah-fm/issues/106 / https://github.com/CodeForPoznan/pah-fm/pull/110

**Comment by monikakrawczak** [comment]
I splited 2 new issues from that one (#148, #149).
This issue should be limited only to sync.

**Comment by adamgajzlerowicz** [comment]
already merged
https://github.com/CodeForPoznan/pah-fm/pull/116
