### ISSUE TITLE
Vuex modules

### ISSUE THREAD

**Issue by pniedzwiedzinski** [CodeForPoznan/pah-fm#421]
We use vuex as our store management, and our store is BIG. I don't really know how it's working 😄.

We could split the store into smaller modules, that will run independently from each other. This hopefully would make the store easier to maintain, test, and in future this might also help with "store migrations".

We actually use modules now, but we store all the methods in common files. So this shouldn't be hard to change

**Comment by pniedzwiedzinski** [comment]
Actually we need store migrations to perform this 😄

**Comment by pniedzwiedzinski** [comment]
I've been thinking about this recently and I came to following. I split the store by data destination and purpose. Thanks to that we will have state and actions divided in category which hopefully would be easier for newcomers to comprehend. Also I want for this module to be independent from each other, so it will be easier to interact.

> NOTE: I put `?` next to the drive_form since I'm not sure where to store it. On the one hand it's the current state of the application, but on the other hand it might contain data that we don't want to lose.

## Modules

### API module

This would store responses from the server so when the network is down the app would still have access to the data. This data is not sensitive and we don't really care about it hence all of this is backed up on the server. I also want to get rid of the `error` field since we don't use it anywhere and maybe we should start thinking about notification system.

- `cars`
- `passengers`
- `drives`
- `projects`

### Session module

This would store the data about current user and tokens. It would be nice to keep the session during the update process.

- `user`
- `token`
- `language`

### Data module

The most sensitive! There will be stored all data that needs to be synced with server. Most of the migration would be related to this module.

- `unsynced_drives`
- `incorrect_drives`
- `drive_form`?

### State module

This would cover the communication between the components of the app. The data in this module wouldn't be persistent so we don't really have to bother about it.

- `drive_form`?
- `drive_hash`
- `isOnline`
- `hash`
- `loginInProgress`

### Migration module [NEW✨]

This would keep track of applied migration to the store and check for the application update.

- `applied_migrations` (#460)
- `current_version` (#462)
- `updateReady`

**Comment by arturtamborski** [comment]
That looks really good!

Regarding `drive_form` - I think that it should belong to Data module.
My reasoning here is that we can treat the partial data typed into the form (and selected car plates) as some sort of the user settings that one can have control over.
Maybe it's not the most _crucial_ part of the data that we store, but it's still one of the main points that user will interact with, so we should have a way of storing it, as opposed to keeping it within State module (which holds temporary information that is not _that_ important).

Another field - `language` IMO shouldn't belong to Session module (rather - Data module).
Language can be considered as a value (setting?) which user inputs, so we should store that for much longer than a lifetime of a session. It's also not related to session in any way known to me.

Also, nitpick - we should use camelCase and stick with it, as that's the territory of JavaScript world :)
So `applied_migrations` -> `appliedMigrations`, etc.

**Comment by pniedzwiedzinski** [comment]
Right, `language` is more important.

> Also, nitpick - we should use camelCase and stick with it, as that's the territory of JavaScript world :) 
> So applied_migrations -> appliedMigrations, etc.

That's the problem with the whole store... it already has a lot of snake-cased names. I hope that when we create the migration system we could easily change it.

**Comment by arturtamborski** [comment]
> That's the problem with the whole store... it already has a lot of snake-cased names. I hope that when we create the migration system we could easily change it.

Oh, I see... Well then, so we've got a target for our first migration :D

**Comment by magul** [comment]
My initial thought here is to store `drive_form` (or `driveForm`) as a member of `state` module. Also don't really know what's the difference between `drives` in `API` module and `unsynced_drives` or 
`incorrect_drives` in `data module (what is `incorrect_drives`?)

**Comment by pniedzwiedzinski** [comment]
> My initial thought here is to store `drive_form` (or `driveForm`) as a member of `state` module. Also don't really know what's the difference between `drives` in `API` module and `unsynced_drives` or
> `incorrect_drives` in `data module (what is `incorrect_drives`?)

The `drives` in `API` would store drives that were already submitted to the backend (hence downloaded from the api endpoint). The `unsynced_drives` stores drives added in offline mode, that are needed to be synced. 

`incorrect_drives` - during the sync, if endpoint returns error, the drive will be moved here from `unsynced_drives`. I don't think we still need that, but it was there.

**Comment by arturtamborski** [comment]
> incorrect_drives - during the sync, if endpoint returns error, the drive will be moved here from unsynced_drives. I don't think we still need that, but it was there.

if we haven't used it until now then I doubt we will use it in the future. I'm happy to remove it.

---

There's one thing that became more clear in #483 - `language` should be set and saved to the value that the user selected. If he hasn't selected any (i.e. during first login) then `language` should default to the user's country that was set in the DB.

**Comment by pniedzwiedzinski** [comment]
I was working on #459 and I encountered a problem with this setup. :disappointed:

### The problem

So as I was moving the jwt token to store I added the `session` module. This token is later used to authorize all the requests. We even created this handy functions that embed it into ever API call. But now before every request it checks for it in store.

This become really a problem if we think about dependencies. The whole purpose of using vuex modules was to divide the store into independent units (easier to test, easier to maintain). But now almost every module at some point will communicate with the backend, hence all modules will be using this token. 

This is definitely not good since this makes every module dependent of `session` module, which breaks the idea of implementing modules. Maybe we should store the token globally or maybe my proposed layout needs to be somehow improved?

**Comment by pniedzwiedzinski** [comment]
## Modules (v2)

### API module

This would store responses from the server so when the network is down the app would still have access to the data. This data is not sensitive and we don't really care about it hence all of this is backed up on the server. I also want to get rid of the `error` field since we don't use it anywhere and maybe we should start thinking about notification system.

- `cars`
- `passengers`
- `drives`
- `projects`

### HTTP session module

This would store the data about current user and tokens. It would be nice to keep the session during the update process. This would also be responsible for HTTP communication with backend. Other modules can use it by `dispatch('session/post', payload, {root:true})`

- `user`
- `token`

#### Actions

- `post`

### Data module

The most sensitive! There will be stored all data that needs to be synced with server. Most of the migration would be related to this module.

- `unsynced_drives`
- `incorrect_drives`
- `drive_form`
- `language`

### State module

This would cover the communication between the components of the app. The data in this module wouldn't be persistent so we don't really have to bother about it.

- `drive_hash`
- `isOnline`
- `hash`
- `loginInProgress`

### Migration module

This would keep track of applied migration to the store and check for the application update.

- `applied_migrations` (#460)
- `current_version` (#462)
- `updateReady`

**Comment by pniedzwiedzinski** [comment]
## Modules (v3)

I thought about it a little bit and probably we can't create entirely independent modules. So I modified a little bit, I think this is final. (Diff from v2: I changed only api and http modules)

### API module

This would store responses from the server so when the network is down the app would still have access to the data. This data is not sensitive and we don't really care about it hence all of this is backed up on the server. I also want to get rid of the `error` field since we don't use it anywhere and maybe we should start thinking about notification system.

- `user` As this a response from api
- `cars`
- `passengers`
- `drives`
- `projects`

### HTTP  module

This module would be responsible for HTTP communication with backend. It would be also responsible for adding the `Authorization` header to requests. Other modules can use it by `dispatch('http/post', payload, {root:true})`

- `token`

#### Actions

- `post`
- `login` - this would return the `user`

### Data module

The most sensitive! There will be stored all data that needs to be synced with server. Most of the migration would be related to this module.

- `unsynced_drives`
- `incorrect_drives`
- `drive_form`
- `language`

### State module

This would cover the communication between the components of the app. The data in this module wouldn't be persistent so we don't really have to bother about it.

- `drive_hash`
- `isOnline`
- `hash`
- `loginInProgress`

### Migration module

This would keep track of applied migration to the store and check for the application update.

- `applied_migrations` (#460)
- `current_version` (#462)
- `updateReady`

**Comment by OtisRed** [comment]
Because of the decision to migrate frontend to React it is not relevant anymore (React store looks completely different).
