### ISSUE TITLE
Verify drive after submit

### ISSUE THREAD

**Issue by pniedzwiedzinski** [CodeForPoznan/pah-fm#424]
Currently, the drive signature is a part of the drive form, so it means that we can alter the drive details after verification. Of course, this means that the drive is unverified since the checksum also changes, but recently @magul pointed out that the drive could be verified after clicking the 'submit' button. Something like this:

![image](https://user-images.githubusercontent.com/19212948/74087886-9a23b980-4a90-11ea-8078-b71f2340e5bf.png)
![image](https://user-images.githubusercontent.com/19212948/74087934-0b636c80-4a91-11ea-8de0-a56421cefbd1.png)

(I used `passenger-input` class so the text is bigger)

**Comment by arturtamborski** [comment]
That's a great idea, one less input box to fill on this rather lengthy form.
Though I'd also like to indicate that the signature is optional by using a placeholder, maybe? Just a suggestion.

**Comment by pniedzwiedzinski** [comment]
We could add a button `Skip verification`

**Comment by arturtamborski** [comment]
Sounds good :)

**Comment by pniedzwiedzinski** [comment]
I wrote down how the submitting process will work now:

-> [user] fills the form
-> [user] clicks submit
-> calculate the checksum of the form
-> save to vuex, redirect to verify view
-> display on verify view
-> [user] inputs confirmation code
-> run `verify` with input value
-> POST the drive with `isVerified`
