### ISSUE TITLE
Show message box when the user 

### ISSUE THREAD

**Issue by arturtamborski** [CodeForPoznan/pah-fm#430]
Currently we show a warning box with a message when drive gets submitted with wrong or empty signature (see picture below)
![image](https://user-images.githubusercontent.com/8676740/74367496-47b90480-4dd2-11ea-87e6-c8c4671cce53.png)

But this (yellow) box will not appear when the signature is correct. I thought that it would be a good idea to add the green confirmation box which informs the Driver that a drive was verified successfully, besides the regular green/gray box which indicates if drive was submitted to server.

**Comment by bckamil** [comment]
@bckamil
