### ISSUE TITLE
Add filter in Django Admin

### ISSUE THREAD

**Issue by monikakrawczak** [CodeForPoznan/pah-fm#436]
In Django Admin add a possibility to filtering by country in CARS and USERS modules.

**Comment by hkaczmarek90** [comment]
I can do it

**Comment by hkaczmarek90** [comment]
In User Admin we have filter by "staff status, superuser status etc." - we want add extra filter by country or we want have only one filter by country ?

**Comment by arturtamborski** [comment]
Extra filer by county, same thing we have in Drives view, the long column of countries listed on the right side.
