### ISSUE TITLE
Fixture creating user for 'behave tests' needs update.

### ISSUE THREAD

**Issue by Ctilhs** [CodeForPoznan/pah-fm#442]
If we have all migrations applied, running `make init-behave` will throw an error.
[Fixture](https://github.com/CodeForPoznan/pah-fm/blob/develop/behave_test_automation/pah_behave/features/data/fixtures.sql) needs an update. 
We made some changes on User model when feature with passenger/driver authorization was implemented.

**Comment by Ctilhs** [comment]
I notice here one problem, but it's not blocking PR fixing it.

We are creating here the user, which is required only for running behave tests.
I think it's related to this issue https://github.com/CodeForPoznan/pah-fm/issues/352

**Comment by Ctilhs** [comment]
Is this user actually used anywhere? :smiley:

**Comment by Ctilhs** [comment]
It looks like this user is not used anymore.

In this case, can we remove `fixtures.sql` and delete it from Makefile?

**Comment by arturtamborski** [comment]
sure, that sounds even better

**Comment by Ctilhs** [comment]
Done https://github.com/CodeForPoznan/pah-fm/pull/443
