### ISSUE TITLE
README.md in Behave tests is outdated.

### ISSUE THREAD

**Issue by Ctilhs** [CodeForPoznan/pah-fm#444]
The path from the description in [README.md](https://github.com/CodeForPoznan/pah-fm/blob/develop/behave_test_automation/README.md#running-behave-tests) does not match what actually we have in the project.

In description:
`~/codeforpoznan/pah-fm/pah_behave`
In project:
`~/codeforpoznan/pah-fm/behave_test_automation/pah_behave`

**Comment by kruczyna** [comment]
I'll take that one

**Comment by kruczyna** [comment]
https://github.com/CodeForPoznan/pah-fm/pull/446
