### ISSUE TITLE
Narrowing the list of countries to those are used

### ISSUE THREAD

**Issue by monikakrawczak** [CodeForPoznan/pah-fm#448]
In Django Admin:
1. Create logic for US -> on the list of countries in filters on all views, user sees only those countries, which are currently used in projects (there are at least car, passenger or project from this country).

**Comment by arturtamborski** [comment]
Can you list the countries that should be available? From what I can tell there is:
- Ukraine
- South Sudan
-???

**Comment by arturtamborski** [comment]
Update: we care about these, for now:
- Ukraine
- South Sudan
- Somalia
- Jemen
- Irak
- Poland

The way it should be developed for now is to list the countries statically, in settings.
https://pypi.org/project/django-countries/#customize-the-country-list

This will later on be improved, but for now we're staying with this option.

**Comment by monikakrawczak** [comment]
New requirements form Ola -> add to the list:
- Kenia
- Switzerland (as a country for test purpose)
