### ISSUE TITLE
Abandon develop branch, switch to master as a default

### ISSUE THREAD

**Issue by arturtamborski** [CodeForPoznan/pah-fm#451]
Develop branch became our master branch, and the master branch is old and rusty. I think that we could merge everything there and switch back to master for good.
I think that maintaining `develop` next to unused `master`:
- serves no purpose (we don't do anything special with this split)
- is confusing to new contributors (why? why not master? :P)
- makes our project special when managing it (you don't pull to default master but to develop)

Hence my idea - one quick merge and even quicker delete right afterwards.
It'll be pain, but less so than going forward with develop.

Or, we can come up with some kind of meaning for it, or just ignore it.

Team, please decide. @CodeForPoznan/pah-devs

**Comment by pniedzwiedzinski** [comment]
It's a good idea!

**Comment by magul** [comment]
Done.
