### ISSUE TITLE
Move everything from localStorage to vuex store

### ISSUE THREAD

**Issue by arturtamborski** [CodeForPoznan/pah-fm#459]
We directly use localStorage in Drive Form View and Save Token (and more?).
We don't have to worry about the values in there for now.

**Comment by pniedzwiedzinski** [comment]
There's a problem with binding input fields with v-model to vuex. There's a package that resolves this issue: https://markus.oberlehner.net/blog/form-fields-two-way-data-binding-and-vuex/
I will test it now.

**Comment by pniedzwiedzinski** [comment]
Looks ok https://codesandbox.io/s/recursing-frog-6rsrw

**Comment by pniedzwiedzinski** [comment]
We need to also move the jwt token into the store.
