### ISSUE TITLE
Start using ISO-639 for translation languages

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/pah-fm#480]
see: https://www.loc.gov/standards/iso639-2/php/code_list.php

**Comment by arturtamborski** [comment]
639-1 or 639-2?

**Comment by arturtamborski** [comment]
So I tried to do this ticket but after some searching I think that it's not worth the trouble.
We are already (unknowingly) following a [ISO-3166-1-alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) standard for country names, enforced by the `flag-icon-css` library for SVG flags ([details](https://github.com/lipis/flag-icon-css#usage)).

So changing the code to ISO-639 will not help us in any way in terms of sticking to some standard. It will also break already existing icons (English and Ukrainian for that matter) and to fix that we would have to create some kind of mapping. To me that sounds like more of a hassle than its worth.

Let's stick to this `ISO-3166-1-alpha-2` standard, it's good enough as any other standard for it's purpose I guess.

**Comment by magul** [comment]
My initial thought here is that it's not so urgent as moving to Vuex modules and then preparing migrations, but as we're going to introduce currencies, we will have 3 entities, that we need somehow to manage (countries, languages, and currencies).

There are already issues to implement countries-currencies mapping, and I believe as we will grow it will make it messier to manage countries and languages with the clear borders between them.
