### ISSUE TITLE
 Somali translation

### ISSUE THREAD

**Issue by monikakrawczak** [CodeForPoznan/pah-fm#483]
Add Somali translation option for Application (driver and passenger).

For a driver, a passenger with a country defined as Somalia set the Somali language as default.
Users can always change the language.

**Comment by monikakrawczak** [comment]
Ola has already got a list of phrases to translate.

**Comment by OlaPAH** [comment]
Hej,
Załączam tłumaczenie :)

[Somali version.txt](https://github.com/CodeForPoznan/pah-fm/files/4551488/Somali.version.txt)
