### ISSUE TITLE
E2E tests

### ISSUE THREAD

**Issue by ghost** [CodeForPoznan/pah-fm#49]
We need to decide if we want to go with WDIO or Behave/Selenium here.

See:
 * WDIO: https://webdriver.io/
 * Behave: https://behave.readthedocs.io/en/latest/
 * Selenium: https://www.seleniumhq.org/

**Comment by jacol12345** [comment]
I'm suspending work on this feature for now as backend needs work!

**Comment by magul** [comment]
@jacol12345 We have just started working on e2e tests with @monikakrawczak and @yellowee - they are building Gherkin scenarios and we were thinking about implementing tests in Behave/Python. Do you have a strong opinion about WebDriver.io here? Can we discuss that on Wednesday?

CC: @w1stler @danutaj23

**Comment by jacol12345** [comment]
Feel free to choose the tool you find best ;)
