### ISSUE TITLE
Fix bug where form fields clear themselves after clicking on dropdown

### ISSUE THREAD

**Issue by arturtamborski** [CodeForPoznan/pah-fm#514]
So that's super weird bug, i suggest cherry picking it by following commits from 2020-04 release.

The general flow for reproducing it is that you'll have to go to add new drive, input some text into the simple form fields (such as "Start location" and "Starting Mileage") and then click on "Project" dropdown. Values from previous fields should disappear.

This bug is reproducible on `dev.pahfm.codeforpoznan.pl`, just follow instructions above, if it doesn't happen then try to add few drives normally and try again after refreshing, it happens 80% of time.

**Comment by juliaanholcer** [comment]
From what I see it is not entirely related to clicking on dropdown, but with the onBlur event of one of the Starting Mileage or Ending Mileage fields.

**Comment by pniedzwiedzinski** [comment]
Solution found, during the "cleaning" of the form it removes everything, instead of emptying object properties. Because of that vuex binding cannot get value from store, so it's set but not visible.
