### ISSUE TITLE
Show Passengers in Drives view

### ISSUE THREAD

**Issue by arturtamborski** [CodeForPoznan/pah-fm#527]
Submitted drives in DrivesView are not displaying the passenger who took part in that drive. We should show it :)

**Comment by mateuszmagulski** [comment]
I can take this issue. 
Can only one passenger take part in drive? From API we receive list of passengers, with one element. 
I want to add information about passenger between "With car" and "Project", is that fine?

**Comment by arturtamborski** [comment]
> I can take this issue.

Great, will assign it to you then :)

> Can only one passenger take part in drive? From API we receive list of passengers, with one element.

Yes, that's the expected behaviour. I know that the code around there might be bit messy but that's because the app supported more than one passenger some time ago, but that has changed. Unfortunately due to the fact that API returns a list you'll have to pull out the actual passenger via array indexing.  
Anyway - exactly one passenger _must_ take part in a drive, that's how it's going to work from now on so that's how I'd like to see it being implemented.

> I want to add information about passenger between "With car" and "Project", is that fine?

Yup, that's fine for me.

We don't have any strict UI rules (yet), I'm expecting some kind of UI redesign anyway, but that will wait till UI team can take a look at the app.


There's another thing which might not be obvious - translations. Please use the ones from DriveFormView for Passenger input box.
