### ISSUE TITLE
Frontend improvements

### ISSUE THREAD

**Issue by monikakrawczak** [CodeForPoznan/pah-fm#559]
- translation ad-hoc loading mechanism
  why: the file weights around 20k right now and it's only getting bigger. App loads it fully though most of the content is not useful to the end user, we can use that fact to load the translations on demand instead. 
- assets are too heavy
  why: assets are not optimised? maybe we shouldn't load the assets along the app but instead do it at the very last moment as they aren't needed that much.

**Comment by arturtamborski** [comment]
First point was partially addressed in: https://github.com/CodeForPoznan/pah-fm/issues/572
It's still not offline-first (the translations are loaded up on every page change) but the dictionary size went down considerably.

Second point will have to be addressed with asset optimization tools during deployment.

**Comment by OtisRed** [comment]
We agreed to close it
