### ISSUE TITLE
LoginView

### ISSUE THREAD

**Issue by monikakrawczak** [CodeForPoznan/pah-fm#567]
Task form 'React Revolution'
- add the view for login (https://github.com/CodeForPoznan/pah-fm/blob/master/frontend/src/views/LoginView.vue)
- use formium/formik (https://github.com/formium/formik)
- use yup for schema validation (https://github.com/jquense/yup)

https://github.com/CodeForPoznan/pah-fm/tree/react-revolution

**Comment by OtisRed** [comment]
It's been done
