### ISSUE TITLE
HomeView

### ISSUE THREAD

**Issue by monikakrawczak** [CodeForPoznan/pah-fm#568]
Task from 'React Revolution'
- add home view (https://github.com/CodeForPoznan/pah-fm/blob/master/frontend/src/views/HomeView.vue)

https://github.com/CodeForPoznan/pah-fm/tree/react-revolution

**Comment by arturtamborski** [comment]
This _seems_ to be done here: https://github.com/CodeForPoznan/pah-fm/pull/580
I don't think there's anything more than the usual PAH statement and we do have that on the react fork so I'll consider this one as finished (can be reopened when we find some missing features).
