### ISSUE TITLE
i18n: language switcher

### ISSUE THREAD

**Issue by jacol12345** [CodeForPoznan/pah-fm#62]
AC:
* Add language switcher with flags.
* Make it remember the choice across sessions (not cleared by logging out)

**Comment by adamgajzlerowicz** [comment]
@lukaszmaterla

**Comment by jacol12345** [comment]
We need to preserve language choice across "sessions"

**Comment by adamgajzlerowicz** [comment]
Language is currently synced with local storage (completed by @lukaszmaterla)

**Comment by jacol12345** [comment]
Perfect, let's close it then
