### ISSUE TITLE
i18n: Translate app

### ISSUE THREAD

**Issue by jacol12345** [CodeForPoznan/pah-fm#63]
Add translations for all languages.

Begin with full Polish translation.

**Comment by magul** [comment]
Ok, @jacol12345 I found #58, so I believe that this task has to track translation progress for targeted languages. I will make sub-issues created for these languages.

**Comment by adamgajzlerowicz** [comment]
duplicate of https://github.com/CodeForPoznan/pah-fm/issues/157
