### ISSUE TITLE
Add logout

### ISSUE THREAD

**Issue by adamgajzlerowicz** [CodeForPoznan/pah-fm#91]
add logout route and hook it up to the nav
AC:
- create logout route
- logout route will remove all session data, but the language switcher config
- update nav (mobile and desktop) so it shows user that is logged in (perhaps a new element for that)
- nav should not show `User: xxxx` Either logout, or user name, whatever is more user friendly 
- if invalid jwt token, redirect to login (currently clears part of local storage)

**Comment by adamgajzlerowicz** [comment]
@lukaszmaterla updated info

**Comment by lukaszmaterla** [comment]
@adamgajzlerowicz ok, thanks

**Comment by adamgajzlerowicz** [comment]
Already merged
https://github.com/CodeForPoznan/pah-fm/pull/138
